SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP PROCEDURE IF EXISTS [dbo].[sp_UpdateClinic]
GO
CREATE PROCEDURE [dbo].[sp_UpdateClinic]
	@Address nvarchar(MAX),
	@Name nvarchar(MAX),
	@Id int
AS
IF NOT EXISTS (SELECT 1 FROM Clinics WHERE Id=@Id)
BEGIN
	RETURN -1
END
BEGIN TRY
	SET NOCOUNT ON;

    UPDATE [dbo].Clinics SET
	[Address] = @Address, [Name] = @Name
	WHERE Id = @Id
	RETURN @@ROWCOUNT
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
GO